[package]
name = "jamtwopool_russell_zometa"
version = "0.1.0"
edition = "2024"

[dependencies]
ode_solvers = "0.6.1"
gnuplot = "0.0.46"
image = "0.25.9"
piston2d-graphics = "0.45.0"
russell_lab = "*"
russell_ode="*"